/**
 * Expo config plugin: put the Android activity in night mode before React
 * Native sets up edge-to-edge, so the system navigation bar is dark.
 *
 * Why: since targetSdk 35/36 the app is drawn edge-to-edge and the navigation
 * bar is transparent. React Native picks its icon colour and contrast scrim
 * from the activity's uiMode (WindowUtil.enableEdgeToEdge:
 * isAppearanceLightNavigationBars = !isDarkMode). Cleanway is dark-only
 * (`userInterfaceStyle: "dark"`), but on a phone in the light system theme the
 * 3-button bar came out as a white strip over the dark tab bar (checked on an
 * Android 16 emulator, 2026-10-08). `expo-system-ui` does not help here: it
 * switches night mode in an activity listener that runs after Expo's
 * edge-to-edge listener, i.e. too late for the bar.
 *
 * The fix is one line before `super.onCreate` in MainActivity: AppCompat then
 * applies MODE_NIGHT_YES while the activity is created, and the edge-to-edge
 * code that runs later sees a dark uiMode. The activity lists `uiMode` in
 * configChanges, so this never recreates it. MainActivity is regenerated by
 * every `expo prebuild`, hence a plugin.
 */
const { withMainActivity } = require("@expo/config-plugins");

const SENTINEL = "cleanway-dark-system-bars";

const LINE =
  `    // ${SENTINEL}: dark-only app; set before super.onCreate so edge-to-edge sees night mode\n` +
  "    androidx.appcompat.app.AppCompatDelegate.setDefaultNightMode(" +
  "androidx.appcompat.app.AppCompatDelegate.MODE_NIGHT_YES)\n";

function patch(contents) {
  if (contents.includes(SENTINEL)) return contents; // already applied
  // The first super.onCreate( inside MainActivity.onCreate. Leave an
  // unrecognised file alone rather than guess.
  const anchor = /\n([ \t]*)super\.onCreate\(/;
  if (!anchor.test(contents)) return contents;
  return contents.replace(anchor, (m) => `\n${LINE}${m.slice(1)}`);
}

module.exports = function withDarkSystemBars(config) {
  return withMainActivity(config, (cfg) => {
    if (cfg.modResults.language !== "kt") return cfg; // Java template unsupported
    cfg.modResults.contents = patch(cfg.modResults.contents);
    return cfg;
  });
};

module.exports._patch = patch;
module.exports.SENTINEL = SENTINEL;
