/**
 * Expo config plugin: a second Android build, "rustore", that checks every
 * incoming SMS on the phone. The browser-downloaded APK stays SMS-free.
 *
 * Why two APKs (founder decision 2026-09-25): Google Play Protect's enhanced
 * fraud protection hard-blocks an APK installed from a browser, a messenger or
 * a file manager when it declares RECEIVE_SMS/READ_SMS (or a notification-
 * listener / accessibility service): "App blocked to protect your device",
 * with no "install anyway". Installs from an app store are not affected. So:
 *
 *   ./gradlew assembleRelease → apk/release/app-release.apk
 *       cleanway.ai/android + GitHub release. NO SMS permission, NO SMS receiver.
 *   ./gradlew assembleRustore → apk/rustore/app-rustore.apk
 *       RuStore only. The release build + RECEIVE_SMS + the SmsReceiver entry
 *       (declared off until the person turns the SMS check on) + the job that
 *       keeps the blocklist fresh for it while the network shield is off.
 *
 * Mechanism: an extra build type, `rustore { initWith release }` — same package
 * (ai.cleanway.app), same release key, same Hermes JS bundle, same ARM-only
 * ABIs, not debuggable. Its ONLY difference is the manifest overlay
 * app/src/rustore/AndroidManifest.xml. Nothing SMS-related goes into the main
 * manifest or app.json `android.permissions`, so the browser APK cannot pick it
 * up by accident, and mobile/scripts/check-apk-permissions.mjs checks both
 * outputs after every build.
 *
 * Two details the build type depends on:
 *  - initWith copies values at the moment it runs, so the block is inserted at
 *    the END of `buildTypes {}`, after `release {}` has been configured by the
 *    template, withReleaseSigning and withAbiFilters — whichever order Expo
 *    runs the plugins in. The copy then carries the real signing config and
 *    the ABI filter.
 *  - `matchingFallbacks = ['release']`: every library (the Expo modules,
 *    react-android, hermes-android) publishes only debug/release variants, and
 *    Gradle cannot resolve them for a "rustore" app variant without it.
 *
 * Fail-safe and idempotent, like withReleaseSigning: a sentinel guards
 * re-application; if the buildTypes/release anchor is missing, build.gradle is
 * left alone and `assembleRustore` fails with "task not found" — loud, never a
 * mis-built APK. The overlay manifest is ours entirely: written when absent or
 * when it carries our sentinel, left alone (with a prebuild warning) if someone
 * replaced it by hand.
 */
const { withAppBuildGradle, withDangerousMod, WarningAggregator } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const SENTINEL = "cleanway-rustore-variant";

/** Where the overlay lives, relative to android/. Build type "rustore" → source set "rustore". */
const MANIFEST_PATH = path.join("app", "src", "rustore", "AndroidManifest.xml");

/** Both classes live in modules/cleanway-vpn and compile into every APK; only this overlay declares them. */
const RECEIVER_CLASS = "ai.cleanway.app.SmsReceiver";
const JOB_CLASS = "ai.cleanway.app.BlocklistRefreshJob";

// Must never contain the text `release {`: withReleaseSigning and
// withAbiFilters find the release build type by the first `release {` after
// `buildTypes {`, and this block sits after it either way.
const BUILD_TYPE_BLOCK = `
        // ${SENTINEL}: \`assembleRustore\` — the RuStore APK, which also checks
        // incoming SMS on the phone. A copy of the release build type (key, JS
        // bundle, ABIs, not debuggable); the only difference is the manifest
        // overlay app/src/rustore/AndroidManifest.xml. The browser APK
        // (assembleRelease) must never declare SMS access: Play Protect
        // hard-blocks sideloaded apps that do. See mobile/plugins/withRustoreVariant.js.
        rustore {
            initWith release
            // Libraries publish only debug/release variants: use their release one.
            matchingFallbacks = ['release']
        }
`;

// The receiver's process: ":sms", on the ":boot" precedent (see the
// BootReceiver comment in the module manifest). Reasons are in the XML itself.
const RUSTORE_MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<!-- ${SENTINEL}: generated by mobile/plugins/withRustoreVariant.js on every
     prebuild. Edit the plugin, not this file.

     RuStore build ONLY (./gradlew assembleRustore). The browser-downloaded APK
     (assembleRelease) must never carry anything below: Play Protect hard-blocks
     sideloaded apps that declare SMS access. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <!-- Least privilege: RECEIVE_SMS only. No READ_SMS (the inbox is never
         read) and no SEND_SMS. -->
    <uses-permission android:name="android.permission.RECEIVE_SMS" />

    <application>
        <!--
          Checks each incoming SMS on the phone; the text is never sent, stored
          or logged.
          exported: SMS_RECEIVED comes from the telephony process, not from us.
          BROADCAST_SMS: only the system holds it, so no app can feed the
          receiver a fake message.
          ":sms" process, like BootReceiver's ":boot". SMS_RECEIVED is an
          ordered foreground broadcast with a 10 s budget that includes starting
          the process. The main process is the React Native app — Firebase, ML
          Kit and Sentry start with it, ~15 s on a cold boot, which is exactly
          when queued messages are delivered — so a cold start there can miss
          the deadline and the message goes unchecked. A bare process also never
          loads the crash and analytics SDKs, so message text cannot end up in a
          crash report. The cost: no access to the main process's memory, and
          SharedPreferences are not safe across processes — so it records into
          its own file store (SmsEventLog), never into BlockLog.
          enabled="false": off until the person turns the SMS check on in the
          app (SmsShield.setEnabled flips the component; the permission stays).
        -->
        <receiver
            android:name="${RECEIVER_CLASS}"
            android:enabled="false"
            android:exported="true"
            android:permission="android.permission.BROADCAST_SMS"
            android:process=":sms">
            <intent-filter>
                <action android:name="android.provider.Telephony.SMS_RECEIVED" />
            </intent-filter>
        </receiver>
        <!--
          Keeps the blocklist fresh for the SMS check while the network shield
          is off (only the running shield refreshed it before). Scheduled only
          while the SMS check is on; fetches the list, sends nothing about the
          person. Main process: it shares the shield's write lock on the list.
        -->
        <service
            android:name="${JOB_CLASS}"
            android:exported="false"
            android:permission="android.permission.BIND_JOB_SERVICE" />
    </application>
</manifest>
`;

/**
 * Index of the `}` closing the block whose `{` is at [open], or -1. Skips
 * string literals and comments, so a brace inside either cannot miscount.
 */
function findBlockEnd(text, open) {
  let depth = 0;
  for (let i = open; i < text.length; i++) {
    const c = text[i];
    if (c === "/" && text[i + 1] === "/") {
      const eol = text.indexOf("\n", i);
      if (eol === -1) return -1;
      i = eol;
    } else if (c === "/" && text[i + 1] === "*") {
      const close = text.indexOf("*/", i + 2);
      if (close === -1) return -1;
      i = close + 1;
    } else if (c === '"' || c === "'") {
      let j = i + 1;
      while (j < text.length && text[j] !== c) j += text[j] === "\\" ? 2 : 1;
      i = j;
    } else if (c === "{") {
      depth++;
    } else if (c === "}") {
      depth--;
      if (depth === 0) return i;
    }
  }
  return -1;
}

function patch(contents) {
  if (contents.includes(SENTINEL)) return contents; // already applied

  const buildTypes = /buildTypes\s*\{/.exec(contents);
  if (!buildTypes) return contents; // unrecognised gradle — leave it entirely alone
  const open = buildTypes.index + buildTypes[0].length - 1;
  const close = findBlockEnd(contents, open);
  if (close === -1) return contents;
  // No release build type to copy: adding `initWith release` would break the build.
  if (!/\brelease\s*\{/.test(contents.slice(open, close))) return contents;

  // Insert just before buildTypes' closing brace, i.e. after `release {}`.
  const lineStart = contents.lastIndexOf("\n", close) + 1;
  const insertAt = contents.slice(lineStart, close).trim() === "" ? lineStart : close;
  return contents.slice(0, insertAt) + BUILD_TYPE_BLOCK + contents.slice(insertAt);
}

/**
 * Write the overlay into [androidRoot]. Returns "written", "unchanged", or
 * "foreign" when a file without our sentinel is there (left untouched).
 */
function writeManifest(androidRoot) {
  const file = path.join(androidRoot, MANIFEST_PATH);
  if (fs.existsSync(file)) {
    const current = fs.readFileSync(file, "utf8");
    if (current === RUSTORE_MANIFEST) return "unchanged";
    if (!current.includes(SENTINEL)) return "foreign";
  }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, RUSTORE_MANIFEST);
  return "written";
}

function withRustoreBuildType(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== "groovy") return cfg; // .kts unsupported
    cfg.modResults.contents = patch(cfg.modResults.contents);
    return cfg;
  });
}

function withRustoreManifest(config) {
  return withDangerousMod(config, [
    "android",
    async (cfg) => {
      if (writeManifest(cfg.modRequest.platformProjectRoot) === "foreign") {
        WarningAggregator.addWarningAndroid(
          SENTINEL,
          `${MANIFEST_PATH} was not written by withRustoreVariant and was left as is. ` +
            "Delete it to get the generated RuStore manifest back.",
        );
      }
      return cfg;
    },
  ]);
}

module.exports = function withRustoreVariant(config) {
  return withRustoreManifest(withRustoreBuildType(config));
};

// Test seams: the pure gradle transform and the overlay writer, so both can be
// verified (idempotent, fail-safe, main manifest untouched) without a prebuild.
module.exports._patch = patch;
module.exports._writeManifest = writeManifest;
module.exports.RUSTORE_MANIFEST = RUSTORE_MANIFEST;
module.exports.MANIFEST_PATH = MANIFEST_PATH;
module.exports.RECEIVER_CLASS = RECEIVER_CLASS;
module.exports.JOB_CLASS = JOB_CLASS;
