"""The billing store — repository interface (plan A.3), two implementations.

    async with store.transaction() as tx:
        sub = await tx.get_subscription(sub_id, for_update=True)
        ...

`MemoryStore` (tests, local demos) serialises every transaction with one
lock; `PostgresStore` (asyncpg) maps to the schema in `migrations/` and
locks rows with SELECT … FOR UPDATE. Service code only ever sees `Tx`.

Rows are the frozen dataclasses of `api/billing/models.py`; the store never
returns a mutable object it keeps.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, AsyncContextManager, Mapping, Optional, Protocol, Sequence

from api.billing.models import (
    AuditRow,
    BillingEventRow,
    ClaimCode,
    Consent,
    Device,
    IdempotentResponse,
    Payment,
    Plan,
    Seat,
    Subscription,
    Trial,
)


class ConflictError(Exception):
    """Optimistic lock lost (row_version moved) or a unique constraint was hit."""


class Tx(Protocol):
    """One unit of work. Every method reads and writes inside the same transaction."""

    # plans
    async def upsert_plan(self, plan: Plan) -> None: ...
    async def list_plans(self, *, active_only: bool = True) -> Sequence[Plan]: ...
    async def get_plan(self, code: str, version: int) -> Optional[Plan]: ...

    # accounts / devices
    async def create_account(self, *, display_label: Optional[str] = None) -> str: ...
    async def create_device(
        self, *, account_id: str, secret_sha256: str, platform: str,
        app_version: Optional[str], legacy_free: bool,
    ) -> Device: ...
    async def get_device(self, device_id: str) -> Optional[Device]: ...
    async def get_device_by_secret_hash(self, secret_sha256: str) -> Optional[Device]: ...
    async def touch_device(self, device_id: str, *, seen_at: datetime, app_version: Optional[str]) -> None: ...

    # trials
    async def get_trial_by_fingerprint(self, fingerprint_hmac: str) -> Optional[Trial]: ...
    async def get_trial_for_device(self, device_id: str) -> Optional[Trial]: ...
    async def create_trial(self, trial: Trial) -> None: ...
    async def rebind_trial(self, fingerprint_hmac: str, device_id: str) -> None: ...   # reinstall: same trial, new device

    # subscriptions
    async def create_subscription(self, sub: Subscription) -> Subscription: ...
    async def get_subscription(self, sub_id: str, *, for_update: bool = False) -> Optional[Subscription]: ...
    async def update_subscription(self, sub: Subscription, *, expected_version: int) -> Subscription: ...
    async def delete_subscription(self, sub_id: str) -> None: ...
    async def get_subscription_by_provider_ref(self, provider: str, provider_subscription_id: str) -> Optional[Subscription]: ...
    async def list_subscriptions_by_msisdn_hmac(self, msisdn_hmac: str) -> Sequence[Subscription]: ...
    async def list_subscriptions_for_account(self, account_id: str) -> Sequence[Subscription]: ...
    async def list_due_renewals(self, *, now: datetime, limit: int = 100) -> Sequence[Subscription]: ...
    async def list_pending_older_than(self, *, cutoff: datetime, limit: int = 100) -> Sequence[Subscription]: ...
    async def list_expiring(self, *, now: datetime, limit: int = 100) -> Sequence[Subscription]: ...
    # ↑ grace ran out, a cancelled period ended, or a fixed-term grant (promo, t2_option) reached its end

    # seats
    async def list_seats(self, sub_id: str, *, active_only: bool = True) -> Sequence[Seat]: ...
    async def get_active_seat_for_device(self, device_id: str) -> Optional[Seat]: ...
    async def add_seat(self, seat: Seat) -> None: ...
    async def release_seat(self, sub_id: str, device_id: str, *, released_at: datetime) -> bool: ...

    # claim codes
    async def create_claim_code(self, code: ClaimCode) -> None: ...
    async def get_claim_code(self, code_hmac: str, *, for_update: bool = False) -> Optional[ClaimCode]: ...
    async def redeem_claim_code(self, code_id: str, *, device_id: str, redeemed_at: datetime) -> bool: ...
    # ↑ single use: False (nothing changed) when the code was already redeemed

    # payments
    async def create_payment(self, payment: Payment) -> Payment: ...   # returns the existing row for a repeated key
    async def get_payment(self, payment_id: str) -> Optional[Payment]: ...
    async def get_payment_by_idempotency_key(self, key: str) -> Optional[Payment]: ...
    async def get_payment_by_provider_id(self, provider: str, provider_payment_id: str) -> Optional[Payment]: ...
    async def update_payment(self, payment: Payment) -> None: ...
    async def list_pending_payments_older_than(self, *, cutoff: datetime, limit: int = 100) -> Sequence[Payment]: ...
    async def list_payments(self, sub_id: str) -> Sequence[Payment]: ...

    # webhooks, consents, audit
    async def insert_event(
        self, *, provider: str, provider_event_id: str, signature_ok: bool, payload_ciphertext: bytes,
        event_ciphertext: Optional[bytes] = None,
    ) -> Optional[int]: ...   # None when (provider, event id) was already stored
    async def mark_event_processed(self, event_id: int, *, processed_at: datetime, outcome: str) -> None: ...
    async def list_retryable_events(self, *, limit: int = 100) -> Sequence[BillingEventRow]: ...
    # ↑ verified events that matched nothing yet (outcome 'unmatched') and carry their normalised form
    async def retry_event(self, event_id: int, *, processed_at: datetime, outcome: str) -> None: ...   # attempts + 1
    async def add_consent(self, consent: Consent) -> Consent: ...
    async def list_consents(self, account_id: str) -> Sequence[Consent]: ...
    async def add_audit(self, *, actor: str, action: str, target: str, meta: Mapping[str, Any]) -> AuditRow: ...
    async def list_audit(self, target: str) -> Sequence[AuditRow]: ...

    # idempotent API responses
    async def get_idempotent_response(self, scope: str, key: str) -> Optional[IdempotentResponse]: ...
    async def reserve_idempotency_key(
        self, scope: str, key: str, *, now: datetime, stale_before: datetime,
    ) -> Optional[IdempotentResponse]: ...
    # ↑ None = the caller now holds the key (new, or an in-progress reservation older than
    #   stale_before taken over); otherwise the existing row, completed or still in progress.
    async def put_idempotent_response(self, response: IdempotentResponse) -> None: ...   # completes a reservation; never overwrites an answer
    async def release_idempotency_key(self, scope: str, key: str) -> None: ...   # drops an in-progress reservation only


class BillingStore(Protocol):
    def transaction(self) -> AsyncContextManager[Tx]: ...
    async def close(self) -> None: ...
