/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Domains
         * @description Check one or more domains for phishing/safety.
         *
         *     Speed tiers:
         *       - Cached: <1ms (Redis)
         *       - Allowlisted: <1ms (Tranco 100K, no API calls)
         *       - Full analysis: 2-5s (14 parallel checks)
         *
         *     Privacy: only domain names processed. Full URLs never logged.
         */
        post: operations["check_domains_api_v1_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/create-checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout
         * @description Create a Stripe Checkout session for subscription.
         */
        post: operations["create_checkout_api_v1_payments_create_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook
         * @description Handle Stripe webhook events.
         */
        post: operations["stripe_webhook_api_v1_payments_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payments/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Customer Portal
         * @description Create Stripe Customer Portal link for managing subscription.
         */
        post: operations["customer_portal_api_v1_payments_portal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/aggregates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Weekly Aggregate
         * @description Submit weekly aggregate numbers from device.
         *     Called once per week by the extension/app.
         *     Server stores ONLY numbers — no URLs, no details.
         */
        post: operations["submit_weekly_aggregate_api_v1_user_aggregates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/percentile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Percentile
         * @description Get user's percentile ranking based on weekly blocks.
         *     "Safer than X% of users" — computed from all users' aggregates.
         */
        get: operations["get_percentile_api_v1_user_percentile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync Score
         * @description Sync security score NUMBER from device.
         *     Score is CALCULATED on device. Server stores the number only.
         *     Details/breakdown stay on device.
         */
        post: operations["sync_score_api_v1_user_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Device
         * @description Register or update device for multi-device sync.
         */
        post: operations["register_device_api_v1_user_device_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Profile
         * @description Get user profile info.
         */
        get: operations["get_profile_api_v1_user_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Domain
         * @description Report a false positive (safe site flagged) or false negative (phishing not caught).
         *     Stored for ML model retraining and manual review.
         */
        post: operations["report_domain_api_v1_feedback_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback/whitelist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Whitelist
         * @description Get user's personal whitelist.
         */
        get: operations["get_whitelist_api_v1_feedback_whitelist_get"];
        put?: never;
        /**
         * Add To Whitelist
         * @description Add a domain to user's personal whitelist (always marked safe).
         */
        post: operations["add_to_whitelist_api_v1_feedback_whitelist_post"];
        /**
         * Remove From Whitelist
         * @description Remove domain from personal whitelist.
         */
        delete: operations["remove_from_whitelist_api_v1_feedback_whitelist_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/check/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Public Check
         * @description Public domain safety check. No auth required.
         *     Rate limited by IP (10/min). Used for SEO pages and embeds.
         *     Returns simplified result without full analysis (fast, no external API calls).
         */
        get: operations["public_check_api_v1_public_check__domain__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Platform Stats
         * @description Global platform statistics for landing page and social proof.
         */
        get: operations["platform_stats_api_v1_public_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/breach/check/{hash_prefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Breach
         * @description k-anonymity breach check.
         *
         *     Send first 5 characters of SHA-1(email) hash.
         *     Returns list of matching hash suffixes with breach counts.
         *     Client compares locally — we never see your full hash.
         */
        get: operations["check_breach_api_v1_breach_check__hash_prefix__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/breach/domain/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Domain Breaches
         * @description Check if a domain has been involved in known data breaches.
         *     Uses HIBP v3 API (requires API key for this endpoint).
         *     Falls back to basic info without key.
         */
        get: operations["check_domain_breaches_api_v1_breach_domain__domain__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/referral/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Referral
         * @description Generate unique referral code for user.
         */
        post: operations["generate_referral_api_v1_referral_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/referral/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Referral Stats
         * @description Get user's referral stats.
         */
        get: operations["referral_stats_api_v1_referral_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/referral/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem Referral
         * @description Redeem a referral code. Gives 7-day Personal trial to redeemer + 7 days to referrer.
         */
        post: operations["redeem_referral_api_v1_referral_redeem_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Org
         * @description Create a new organization. Requires business tier.
         */
        post: operations["create_org_api_v1_org_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/{org_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Org Dashboard
         * @description Organization threat dashboard.
         *     Shows aggregate stats — individual user data is NOT visible to admins.
         */
        get: operations["org_dashboard_api_v1_org__org_id__dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Member
         * @description Add member to organization.
         */
        post: operations["add_member_api_v1_org__org_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/{org_id}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Launch Simulation
         * @description Launch phishing simulation campaign.
         *
         *     Templates:
         *       - generic_phishing: "Your account will be suspended"
         *       - credential_harvest: Fake login page
         *       - invoice_scam: Fake invoice attachment
         *       - ceo_fraud: "CEO" requests urgent wire transfer
         *
         *     Privacy: simulations only target verified org member emails.
         *     Results track who clicked/reported — for training, not punishment.
         */
        post: operations["launch_simulation_api_v1_org__org_id__simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/{org_id}/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Simulations
         * @description List all phishing simulation campaigns for this org.
         */
        get: operations["list_simulations_api_v1_org__org_id__simulations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/org/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description List available phishing simulation templates.
         */
        get: operations["list_templates_api_v1_org_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/for-country": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prices For Country
         * @description Return pricing for all plans (personal, family, business) × intervals (monthly, yearly)
         *     for the given country's PPP tier.
         */
        get: operations["prices_for_country_api_v1_pricing_for_country_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pricing/tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pricing Tiers
         * @description Full tier reference — which countries are in each tier + base prices.
         */
        get: operations["pricing_tiers_api_v1_pricing_tiers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check that verifies dependencies and circuit breaker states.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddMemberRequest */
        AddMemberRequest: {
            /** Email */
            email: string;
            /**
             * Role
             * @default member
             */
            role: string;
        };
        /**
         * CheckRequest
         * @example {
         *       "domains": [
         *         "google.com",
         *         "paypa1-verify.tk"
         *       ]
         *     }
         */
        CheckRequest: {
            /**
             * Domains
             * @description Domains to check
             */
            domains: string[];
        };
        /** CheckResponse */
        CheckResponse: {
            /** Results */
            results: components["schemas"]["DomainResult"][];
            /** Checked At */
            checked_at: string;
            /** Api Calls Remaining */
            api_calls_remaining?: number | null;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /** Plan */
            plan: string;
            /**
             * Success Url
             * @default https://cleanway.ai/success
             */
            success_url: string;
            /**
             * Cancel Url
             * @default https://cleanway.ai/pricing
             */
            cancel_url: string;
        };
        /** CheckoutResponse */
        CheckoutResponse: {
            /** Checkout Url */
            checkout_url: string;
        };
        /**
         * ConfidenceLevel
         * @enum {string}
         */
        ConfidenceLevel: "high" | "medium" | "low";
        /** CreateOrgRequest */
        CreateOrgRequest: {
            /** Name */
            name: string;
        };
        /** DeviceRegister */
        DeviceRegister: {
            /** Device Hash */
            device_hash: string;
            /** Platform */
            platform: string;
            /**
             * App Version
             * @default 0.1.0
             */
            app_version: string;
        };
        /** DomainReason */
        DomainReason: {
            /** Signal */
            signal: string;
            /** Detail */
            detail: string;
            /** Weight */
            weight: number;
        };
        /** DomainResult */
        DomainResult: {
            /** Domain */
            domain: string;
            /** Score */
            score: number;
            level: components["schemas"]["RiskLevel"];
            /** @default medium */
            confidence: components["schemas"]["ConfidenceLevel"];
            /** Reasons */
            reasons: components["schemas"]["DomainReason"][];
            /** Domain Age Days */
            domain_age_days?: number | null;
            /** Has Ssl */
            has_ssl?: boolean | null;
            /** Ssl Issuer */
            ssl_issuer?: string | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail: components["schemas"]["ValidationError"][];
        };
        /** PercentileResponse */
        PercentileResponse: {
            /** Percentile */
            percentile: number;
            /** Total Blocks */
            total_blocks: number;
            /** Bracket */
            bracket: string;
        };
        /** PlanIntervals */
        PlanIntervals: {
            monthly: components["schemas"]["PricePoint"];
            yearly: components["schemas"]["PricePoint"];
        };
        /**
         * PricePoint
         * @description One price (monthly or yearly) for a single plan in a single tier.
         */
        PricePoint: {
            /**
             * Amount
             * @description Display price in USD (monthly or yearly total)
             */
            amount: number;
            /**
             * Monthly Equivalent
             * @description Equivalent monthly rate for comparison
             */
            monthly_equivalent: number;
            /**
             * Interval
             * @enum {string}
             */
            interval: "monthly" | "yearly";
            /**
             * Stripe Price Id
             * @description Stripe price ID for checkout session
             */
            stripe_price_id: string;
        };
        /** PricingForCountryResponse */
        PricingForCountryResponse: {
            /**
             * Country
             * @description Echoed ISO 3166-1 alpha-2 country code (uppercased). None when no cc was provided.
             */
            country?: string | null;
            /**
             * Tier
             * @description PPP pricing tier. 1=Premium, 2=Base (default), 3=Mid-emerging, 4=Affordable.
             * @enum {integer}
             */
            tier: 1 | 2 | 3 | 4;
            /**
             * Currency
             * @default USD
             * @constant
             */
            currency: "USD";
            /** Plans */
            plans: {
                [key: string]: components["schemas"]["PlanIntervals"];
            };
            messaging: components["schemas"]["PricingMessaging"];
        };
        /** PricingMessaging */
        PricingMessaging: {
            /**
             * Blocking Is Free Forever
             * @description Ethical invariant: scam site blocking never requires payment. Always true.
             */
            blocking_is_free_forever: boolean;
            /**
             * Free Threat Threshold
             * @description Number of detailed threat explanations given free. After this, paywall gates the DETAILS (not the block itself).
             */
            free_threat_threshold: number;
            /** What Paid Unlocks */
            what_paid_unlocks: string[];
        };
        /** PricingTiersResponse */
        PricingTiersResponse: {
            /** Tiers */
            tiers: {
                [key: string]: components["schemas"]["TierDescription"];
            };
            /** Base Prices Usd Monthly */
            base_prices_usd_monthly: {
                [key: string]: number;
            };
            /** Notes */
            notes: {
                [key: string]: string;
            };
        };
        /** ProfileResponse */
        ProfileResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string | null;
            /** Tier */
            tier: string;
            /** Devices */
            devices: number;
            /** Member Since */
            member_since: string | null;
        };
        /** RedeemRequest */
        RedeemRequest: {
            /** Code */
            code: string;
        };
        /** ReportRequest */
        ReportRequest: {
            /** Domain */
            domain: string;
            /**
             * Report Type
             * @description false_positive or false_negative
             */
            report_type: string;
            /** Current Score */
            current_score?: number | null;
            /** Comment */
            comment?: string | null;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "safe" | "caution" | "dangerous";
        /** ScoreSync */
        ScoreSync: {
            /** Score */
            score: number;
        };
        /** SimulationRequest */
        SimulationRequest: {
            /**
             * Template
             * @default generic_phishing
             */
            template: string;
            /** Target Emails */
            target_emails: string[];
            /**
             * Sender Name
             * @default IT Security
             */
            sender_name: string;
            /**
             * Subject
             * @default Action Required: Verify Your Account
             */
            subject: string;
        };
        /** TierDescription */
        TierDescription: {
            /** Name */
            name: string;
            /** Multiplier */
            multiplier: number;
            /**
             * Countries
             * @description List of ISO country codes, or a human-readable note for tier 2 (default).
             */
            countries: unknown;
            /** Examples */
            examples: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeeklyAggregateSubmit */
        WeeklyAggregateSubmit: {
            /** Total Checks */
            total_checks: number;
            /** Total Blocks */
            total_blocks: number;
            /**
             * Total Warnings
             * @default 0
             */
            total_warnings: number;
            /**
             * Total Trackers
             * @default 0
             */
            total_trackers: number;
            /** Score */
            score?: number | null;
        };
        /** WhitelistRequest */
        WhitelistRequest: {
            /** Domain */
            domain: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    check_domains_api_v1_check_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_api_v1_payments_create_checkout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_api_v1_payments_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    customer_portal_api_v1_payments_portal_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_weekly_aggregate_api_v1_user_aggregates_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyAggregateSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_percentile_api_v1_user_percentile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PercentileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_score_api_v1_user_score_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreSync"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_device_api_v1_user_device_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_user_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_domain_api_v1_feedback_report_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_whitelist_api_v1_feedback_whitelist_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_whitelist_api_v1_feedback_whitelist_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhitelistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_whitelist_api_v1_feedback_whitelist_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhitelistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_check_api_v1_public_check__domain__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    platform_stats_api_v1_public_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    check_breach_api_v1_breach_check__hash_prefix__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                hash_prefix: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_domain_breaches_api_v1_breach_domain__domain__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_referral_api_v1_referral_generate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    referral_stats_api_v1_referral_stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeem_referral_api_v1_referral_redeem_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_org_api_v1_org_create_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    org_dashboard_api_v1_org__org_id__dashboard_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_member_api_v1_org__org_id__members_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    launch_simulation_api_v1_org__org_id__simulate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_simulations_api_v1_org__org_id__simulations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_org_templates_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prices_for_country_api_v1_pricing_for_country_get: {
        parameters: {
            query?: {
                /** @description ISO 3166-1 alpha-2 country code. Omit for default tier 2 (base) pricing. */
                cc?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingForCountryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pricing_tiers_api_v1_pricing_tiers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PricingTiersResponse"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
