import type { Metadata } from "next";

import { getTranslations, setRequestLocale } from "next-intl/server";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import { InstallButtons } from "@/components/InstallButtons";
import { PrimaryInstallLink } from "@/components/PrimaryInstallLink";
import { loadLiveRecall } from "@/lib/live-recall";
import { localePath } from "@/lib/locale-path";
import { billingMessageArgs } from "@/lib/billing";
import { BILLING_TERMS, pricingVariantFor } from "@/lib/billing-config";
import { routing, type Locale } from "@/i18n/routing";

const SITE_URL = "https://cleanway.ai";

function homeUrlFor(locale: Locale | string): string {
  return locale === routing.defaultLocale ? `${SITE_URL}/` : `${SITE_URL}/${locale}/`;
}

interface HomeProps {
  params: Promise<{ locale: string }>;
}

export async function generateMetadata({ params }: HomeProps): Promise<Metadata> {
  const { locale } = await params;
  const isLocaleKnown = (routing.locales as readonly string[]).includes(locale);
  const safeLocale: Locale = isLocaleKnown ? (locale as Locale) : routing.defaultLocale;
  setRequestLocale(safeLocale);
  const meta = await getTranslations({ locale: safeLocale, namespace: "Meta" });
  const hero = await getTranslations({ locale: safeLocale, namespace: "Hero" });
  const canonical = homeUrlFor(safeLocale);

  // hreflang map for the homepage — every locale + x-default
  const languages: Record<string, string> = {};
  for (const loc of routing.locales) languages[loc] = homeUrlFor(loc as Locale);
  languages["x-default"] = homeUrlFor(routing.defaultLocale);

  // This is also the Telegram / WhatsApp link preview, so it has to be in the
  // page's language and say only what the product does today.
  const title = `Cleanway — ${hero("title_part1")} ${hero("title_part2")}`.trim();
  const description = meta("description");

  return {
    title,
    description,
    metadataBase: new URL(SITE_URL),
    alternates: { canonical, languages },
    openGraph: {
      title,
      description,
      url: canonical,
      siteName: "Cleanway",
      type: "website",
      locale: safeLocale,
      // Reference the static OG image generated by app/[locale]/opengraph-image.tsx.
      // generateMetadata() overrides the file-convention auto-merge in Next.js 15,
      // so we wire the route URL explicitly to keep social shares branded.
      images: [{ url: "/opengraph-image", width: 1200, height: 630, alt: "Cleanway" }],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      site: "@cleanwayai",
      images: ["/opengraph-image"],
    },
    robots: {
      index: true,
      follow: true,
      googleBot: { index: true, follow: true, "max-image-preview": "large" },
    },
  };
}

interface FeatureItem {
  icon: string;
  title: string;
  desc: string;
}

interface HowItWorksStep {
  step: string;
  title: string;
  desc: string;
}

interface TestimonialItem {
  q: string;
  n: string;
  r: string;
}

interface FaqItem {
  q: string;
  a: string;
}

export default async function Home({ params }: HomeProps) {
  const { locale } = await params;
  setRequestLocale(locale);
  const nav = await getTranslations("Nav");
  const hero = await getTranslations("Hero");
  const meta = await getTranslations("Meta");
  const install = await getTranslations("Install");
  const features = await getTranslations("Features");
  const how = await getTranslations("HowItWorks");
  const pricing = await getTranslations("PricingTeaser");
  const privacy = await getTranslations("Privacy");
  const testimonials = await getTranslations("Testimonials");
  const faq = await getTranslations("FAQ");
  const cta = await getTranslations("FinalCta");
  const footer = await getTranslations("Footer");
  const support = await getTranslations("Support");
  // Live phishing-recall number from the most recent weekly benchmark. Null
  // until a run clears the quality gate — then there is no badge at all rather
  // than a number nobody measured.
  const liveRecall = await loadLiveRecall();
  // The home page describes the free Android app, so its pricing block says
  // what is free — everywhere. The old plan cards sold extension features
  // (link badges, "10 API checks/day") and a 14-day trial nobody on Android
  // can get. Where paid plans exist at all, a link leads to /pricing; Russian
  // visitors cannot buy them (Stripe) and get no link — until the operator-
  // billed subscription is switched on, when the block names it instead.
  const pricingVariant = pricingVariantFor({ locale });
  const showPlansLink = pricingVariant !== "free";
  const teaser = {
    heading: pricingVariant === "operator" ? pricing("operator.heading") : pricing("free_only_heading"),
    body:
      pricingVariant === "operator" ? pricing("operator.body", billingMessageArgs(BILLING_TERMS))
      : pricingVariant === "stripe" ? pricing("free_body_with_plans")
      : pricing("free_only_body"),
    plansLink: pricingVariant === "operator" ? pricing("operator.plans_link") : pricing("plans_link"),
  };
  const href = (path: string) => localePath(locale, path);

  const featureItems = features.raw("items") as FeatureItem[];
  const howSteps = how.raw("steps") as HowItWorksStep[];
  const privacyServerItems = privacy.raw("server_items") as string[];
  const privacyDeviceItems = privacy.raw("device_items") as string[];
  const testimonialItems = testimonials.raw("items") as TestimonialItem[];
  const faqItems = faq.raw("items") as FaqItem[];

  return (
    <div className="min-h-screen bg-[#0f172a] text-slate-200 overflow-x-clip">
      {/* Skip-link — keyboard users bypass the sticky nav. WCAG 2.4.1. */}
      <a href="#main" className="skip-link">Skip to main content</a>
      {/* Nav */}
      <nav aria-label="Primary" className="sticky top-0 z-50 bg-[#0f172a]/95 backdrop-blur-md border-b border-slate-800">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <span className="text-xl font-extrabold text-white">Cleanway</span>
          <div className="hidden md:flex items-center gap-5">
            <a href="#features" className="text-sm text-slate-400 hover:text-white transition">{nav("features")}</a>
            <a href={href("/pricing")} className="text-sm text-slate-400 hover:text-white transition">{nav("pricing")}</a>
            <a href="#privacy" className="text-sm text-slate-400 hover:text-white transition">{nav("privacy")}</a>
            <a href={href("/support")} className="text-sm text-slate-400 hover:text-white transition">{nav("support")}</a>
            <LanguageSwitcher />
            <PrimaryInstallLink data-testid="primary-install-nav" androidLabel={nav("install_android")} className="bg-green-500 text-green-950 px-5 py-2 rounded-lg text-sm font-bold hover:bg-green-400 transition">
              {nav("install")}
            </PrimaryInstallLink>
          </div>
          {/* Mobile menu button */}
          <div className="md:hidden flex items-center gap-2">
            <LanguageSwitcher />
            <PrimaryInstallLink data-testid="primary-install-nav-mobile" androidLabel={nav("install_android_short")} className="bg-green-500 text-green-950 px-4 py-2 rounded-lg text-sm font-bold">
              {nav("install_short")}
            </PrimaryInstallLink>
          </div>
        </div>
      </nav>

      {/* Hero — also serves as the skip-link target / main landmark anchor. */}
      <main id="main">
      <section className="pt-24 pb-16 px-6 text-center">
        <div className="max-w-3xl mx-auto animate-in">
          {liveRecall && (
            <a
              href={href("/transparency/methodology")}
              className="inline-block max-w-full bg-green-500/10 text-green-400 border border-green-500/30 px-4 py-1.5 rounded-full text-sm font-semibold mb-8 hover:bg-green-500/20 transition"
            >
              {hero("badge", { recall: liveRecall.pct })}
            </a>
          )}
          <h1 className="text-4xl md:text-6xl font-extrabold text-white leading-tight mb-6 break-words max-w-full">
            {hero("title_part1")}<br />
            <span className="gradient-text">{hero("title_part2")}</span>
          </h1>
          <p className="text-lg text-slate-400 mb-8 max-w-2xl mx-auto">{hero("subtitle")}</p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <PrimaryInstallLink data-testid="primary-install-hero" androidLabel={hero("cta_android")} className="bg-green-500 text-green-950 px-8 py-4 rounded-xl text-lg font-bold hover:bg-green-400 transition glow-hover">
              {hero("cta_primary")}
            </PrimaryInstallLink>
            <a href="#how" className="border border-slate-600 text-slate-300 px-8 py-4 rounded-xl text-lg font-semibold hover:border-slate-400 transition">
              {hero("cta_secondary")}
            </a>
          </div>
          <div className="mt-6 space-y-3">
            <p className="text-xs uppercase tracking-wide text-slate-500">{install("mobile_label")}</p>
            <InstallButtons platforms={["android", "ios"]} size="sm" />
            <p className="text-xs uppercase tracking-wide text-slate-500 mt-4">{install("browser_label")}</p>
            <InstallButtons platforms={["chrome", "firefox", "edge", "safari"]} size="sm" />
          </div>
          <p className="text-xs text-slate-400 mt-6">{hero("cta_footer")}</p>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl md:text-4xl font-extrabold text-white text-center mb-14">{features("heading")}</h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 stagger">
            {featureItems.map((item) => (
              <div key={item.title} className="bg-slate-800/50 rounded-2xl p-6 hover:bg-slate-800 transition">
                <span aria-hidden="true" className="text-3xl mb-3 block">{item.icon}</span>
                <h3 className="text-lg font-bold text-white mb-2">{item.title}</h3>
                <p className="text-sm text-slate-400 leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how" className="py-20 px-6 bg-[#0b1120]">
        <h2 className="text-3xl font-extrabold text-white text-center mb-14">{how("heading")}</h2>
        <div className="flex flex-col md:flex-row justify-center gap-12 max-w-3xl mx-auto stagger">
          {howSteps.map((s) => (
            <div key={s.step} className="text-center flex-1">
              <div aria-hidden="true" className="w-14 h-14 rounded-full bg-green-500/10 text-green-400 flex items-center justify-center text-xl font-extrabold mx-auto mb-4">{s.step}</div>
              <h3 className="text-lg font-bold text-white mb-2">{s.title}</h3>
              <p className="text-sm text-slate-400">{s.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-20 px-6">
        <div className="max-w-2xl mx-auto text-center bg-slate-800/50 rounded-2xl p-8">
          <h2 className="text-3xl font-extrabold text-white mb-4">{teaser.heading}</h2>
          <p className="text-slate-400 leading-relaxed mb-8">{teaser.body}</p>
          <a data-testid="free-only-android" href={href("/android")} className="inline-block bg-green-500 text-green-950 px-8 py-3 rounded-xl font-bold hover:bg-green-400 transition">
            {pricing("free_only_cta")}
          </a>
          {showPlansLink && (
            <p className="mt-6">
              <a data-testid="home-plans-link" href={href("/pricing")} className="text-sm text-green-400 hover:text-green-300 underline">
                {teaser.plansLink}
              </a>
            </p>
          )}
        </div>
      </section>

      {/* Privacy */}
      <section id="privacy" className="py-20 px-6 bg-[#0b1120]">
        <div className="max-w-4xl mx-auto">
          <h2 className="text-3xl font-extrabold text-white text-center mb-14">{privacy("heading")}</h2>
          <div className="grid md:grid-cols-2 gap-6">
            <div className="bg-slate-800/50 rounded-2xl p-8">
              <h3 className="text-lg font-bold text-white mb-4">{privacy("server_heading")}</h3>
              <ul className="space-y-2 text-sm text-slate-400">
                {privacyServerItems.map((item) => <li key={item}>{item}</li>)}
              </ul>
              <p className="text-sm text-green-400 italic mt-4">{privacy("server_note")}</p>
            </div>
            <div className="bg-slate-800/50 rounded-2xl p-8">
              <h3 className="text-lg font-bold text-white mb-4">{privacy("device_heading")}</h3>
              <ul className="space-y-2 text-sm text-slate-400">
                {privacyDeviceItems.map((item) => <li key={item}>{item}</li>)}
              </ul>
              <p className="text-sm text-green-400 italic mt-4">{privacy("device_note")}</p>
            </div>
          </div>
          {/* The third party nobody expects: with protection on, the phone's
              DNS lookups for unblocked sites go to Cloudflare or Quad9. */}
          <div data-testid="privacy-dns" className="bg-slate-800/50 rounded-2xl p-8 mt-6">
            <h3 className="text-lg font-bold text-white mb-2">{privacy("dns_heading")}</h3>
            <p className="text-sm text-slate-400 leading-relaxed">{privacy("dns_note")}</p>
          </div>
          <p className="text-center mt-8">
            <a href={href("/privacy-policy")} className="text-sm text-green-400 hover:text-green-300 underline">{support("privacy_link")}</a>
          </p>
        </div>
      </section>

      {/* Principles */}
      <section className="py-20 px-6">
        <h2 className="text-3xl font-extrabold text-white text-center mb-14">{testimonials("heading")}</h2>
        <div className="grid md:grid-cols-3 gap-5 max-w-5xl mx-auto stagger">
          {testimonialItems.map((item, i) => (
            <div key={i} data-testid="testimonial-card" className="bg-slate-800/50 rounded-2xl p-6">
              <p className="text-slate-200 text-[15px] leading-relaxed mb-4">{item.q}</p>
              <p className="text-sm font-semibold text-green-400">{item.n}</p>
              {item.r ? <p className="text-xs text-slate-500">{item.r}</p> : null}
            </div>
          ))}
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 px-6 bg-[#0b1120]">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-extrabold text-white text-center mb-14">{faq("heading")}</h2>
          {faqItems.map((item, i) => (
            <details key={i} className="bg-slate-800/50 rounded-xl px-6 py-4 mb-2 group">
              <summary className="text-[15px] font-semibold text-white cursor-pointer">{item.q}</summary>
              <p className="text-sm text-slate-400 leading-relaxed mt-3 pt-3 border-t border-slate-700">{item.a}</p>
            </details>
          ))}
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20 px-6 text-center">
        <h2 className="text-3xl font-extrabold text-white mb-4">{cta("title")}</h2>
        <p className="text-lg text-slate-400 mb-8">{cta("subtitle")}</p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <PrimaryInstallLink data-testid="primary-install-final" androidLabel={hero("cta_android")} className="bg-green-500 text-green-950 px-8 py-4 rounded-xl text-lg font-bold hover:bg-green-400 transition glow-hover">
            {cta("cta_primary")}
          </PrimaryInstallLink>
          <a href={href("/business")} className="border border-slate-600 text-slate-300 px-8 py-4 rounded-xl text-lg font-semibold hover:border-slate-400 transition">
            {cta("cta_business")}
          </a>
        </div>
      </section>

      </main>
      {/* Rich snippets — Organization + SoftwareApplication + FAQPage */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@graph": [
              {
                "@type": "Organization",
                "@id": `${SITE_URL}#organization`,
                name: "Cleanway",
                url: SITE_URL,
                logo: `${SITE_URL}/icon.png`,
                description: meta("description"),
                sameAs: [
                  "https://twitter.com/cleanwayai",
                  "https://github.com/AlexMos555/linkshield",
                ],
              },
              {
                "@type": "WebSite",
                "@id": `${SITE_URL}#website`,
                url: SITE_URL,
                name: "Cleanway",
                publisher: { "@id": `${SITE_URL}#organization` },
                inLanguage: locale,
                potentialAction: {
                  "@type": "SearchAction",
                  target: {
                    "@type": "EntryPoint",
                    urlTemplate: `${SITE_URL}/check?q={search_term_string}`,
                  },
                  "query-input": "required name=search_term_string",
                },
              },
              {
                "@type": "SoftwareApplication",
                name: "Cleanway",
                applicationCategory: "SecurityApplication",
                // Only what can be installed today (lib/install-urls.ts).
                operatingSystem: "Android",
                offers: {
                  "@type": "Offer",
                  price: "0",
                  priceCurrency: "USD",
                  availability: "https://schema.org/InStock",
                },
                description: meta("description"),
                url: SITE_URL,
              },
              {
                "@type": "FAQPage",
                mainEntity: faqItems.map((item) => ({
                  "@type": "Question",
                  name: item.q,
                  acceptedAnswer: { "@type": "Answer", text: item.a },
                })),
              },
            ],
          }),
        }}
      />

      {/* Footer */}
      <footer className="border-t border-slate-800 py-10 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <p className="text-lg font-extrabold text-white mb-4">{footer("brand")}</p>
          <div className="flex flex-wrap justify-center gap-x-6 gap-y-2 mb-4">
            <a href={href("/privacy-policy")} className="text-sm text-slate-400 hover:text-white transition">{footer("privacy")}</a>
            <a href={href("/terms")} className="text-sm text-slate-400 hover:text-white transition">{footer("terms")}</a>
            <a href={href("/transparency/methodology")} className="text-sm text-slate-400 hover:text-white transition">{footer("methodology")}</a>
            <a href={href("/support")} className="text-sm text-slate-400 hover:text-white transition">{footer("contact")}</a>
            <a href="https://github.com/AlexMos555/linkshield" className="text-sm text-slate-400 hover:text-white transition">{footer("github")}</a>
          </div>
          <p className="text-xs text-slate-600">&copy; 2026 Cleanway. {footer("tagline")}</p>
        </div>
      </footer>
    </div>
  );
}
