#!/usr/bin/env python3
"""Build the Android VPN module's bundled assets from data/.

  mobile/modules/cleanway-vpn/android/src/main/assets/popular_veto.txt
    Tranco top-10k MINUS public suffixes / shared platforms. The phone's
    BlockList refuses to block any listed name whose registrable is here —
    a last line of defence against a bad publish. Public suffixes are removed
    on purpose: `github.io` is top-10k, but `evil.github.io` is one tenant's
    site and MUST stay blockable.

  mobile/modules/cleanway-vpn/android/src/main/assets/root_zone_tlds.txt
    Every TLD in the IANA root zone (data/iana_tlds.txt, a verbatim copy of
    https://data.iana.org/TLD/tlds-alpha-by-domain.txt), lowercased, with each
    IDN TLD also written in Unicode (xn--p1ai AND рф) because an SMS carries
    the Unicode form. The message check's LinkExtractor accepts a link written
    without http:// only when it ends in one of these. Refresh: download the
    IANA file over data/iana_tlds.txt, then rebuild.

Usage: python3 scripts/build_mobile_assets.py [--check]
"""
from __future__ import annotations

import codecs
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOP10K = ROOT / "data" / "top_10k.json"
PSL_TOP = ROOT / "data" / "public_suffixes_in_top.json"
ASSETS = ROOT / "mobile" / "modules" / "cleanway-vpn" / "android" / "src" / "main" / "assets"
OUT = ASSETS / "popular_veto.txt"
OUT_SHARED = ASSETS / "shared_suffixes.txt"
IANA_TLDS = ROOT / "data" / "iana_tlds.txt"
OUT_TLDS = ASSETS / "root_zone_tlds.txt"

# Mirror of scripts/refresh_dangerous_domains.py HOSTING_PLATFORMS ∪ scoring.HOSTING_PLATFORMS
# apexes that are top-10k but whose subdomains are tenants.
SHARED_APEXES = {
    "github.io", "gitlab.io", "blogspot.com", "wordpress.com", "wixsite.com", "weebly.com",
    "webflow.io", "netlify.app", "vercel.app", "pages.dev", "workers.dev", "web.app",
    "firebaseapp.com", "appspot.com", "azurewebsites.net", "herokuapp.com", "cloudfront.net",
    "myshopify.com", "notion.site", "carrd.co", "000webhostapp.com", "duckdns.org", "us.org",
}


def build() -> list[str]:
    raw = json.loads(TOP10K.read_text())
    names = {d.lower() for d in (raw.keys() if isinstance(raw, dict) else raw)}
    psl_top = {d.lower() for d in json.loads(PSL_TOP.read_text())} if PSL_TOP.exists() else set()
    return sorted(names - psl_top - SHARED_APEXES)


def build_shared() -> list[str]:
    """Suffixes under which a name is ONE TENANT's site.

    The phone needs these because the popular veto works on the registrable
    domain: `best10cdn.blob.core.windows.net` has registrable `windows.net`,
    which is top-10k, so the veto cancelled the block — 783 of the 1,548
    tenant suffixes the publisher targets were silently un-blockable on the
    phone (found 2026-08-19 by simulating the shipped veto over the live
    artifact). With this set the phone can tell "Microsoft's own name" from
    "someone's bucket on Microsoft's platform".
    """
    psl_top = {d.lower() for d in json.loads(PSL_TOP.read_text())} if PSL_TOP.exists() else set()
    return sorted(psl_top | SHARED_APEXES)


def build_root_zone() -> tuple[str, list[str]]:
    """The IANA root zone as the phone reads it: (IANA version line, TLDs).

    Each xn-- TLD is followed by its Unicode spelling — decoded with the
    punycode codec itself, not the idna one, which rejects some valid IDN
    labels — so the extractor matches "рф" as written without punycoding
    every dotted word in a message.
    """
    lines = IANA_TLDS.read_text().splitlines()
    version = lines[0].lstrip("# ").strip() if lines and lines[0].startswith("#") else "unknown"
    out: list[str] = []
    for line in lines:
        tld = line.strip().lower()
        if not tld or tld.startswith("#"):
            continue
        out.append(tld)
        if tld.startswith("xn--"):
            out.append(codecs.decode(tld[4:].encode("ascii"), "punycode"))
    if len(out) < 1000:
        raise SystemExit(f"{IANA_TLDS.relative_to(ROOT)}: only {len(out)} TLDs — truncated download?")
    return version, out


def main() -> int:
    lines = build()
    shared = build_shared()
    shared_text = "# GENERATED by scripts/build_mobile_assets.py — do not edit\n" + "\n".join(shared) + "\n"
    text = "# GENERATED by scripts/build_mobile_assets.py — do not edit\n" + "\n".join(lines) + "\n"
    tld_version, tlds = build_root_zone()
    tlds_text = (
        "# GENERATED by scripts/build_mobile_assets.py from data/iana_tlds.txt — do not edit\n"
        f"# IANA {tld_version}\n" + "\n".join(tlds) + "\n"
    )
    if "--check" in sys.argv:
        stale = []
        if (OUT.read_text() if OUT.exists() else "") != text:
            stale.append(OUT)
        if (OUT_SHARED.read_text() if OUT_SHARED.exists() else "") != shared_text:
            stale.append(OUT_SHARED)
        if (OUT_TLDS.read_text() if OUT_TLDS.exists() else "") != tlds_text:
            stale.append(OUT_TLDS)
        if stale:
            for f in stale:
                print(f"STALE: {f.relative_to(ROOT)}")
            return 1
        print(f"OK: {len(lines)} popular names, {len(shared)} shared suffixes, {len(tlds)} root-zone TLDs")
        return 0
    ASSETS.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    OUT_SHARED.write_text(shared_text)
    OUT_TLDS.write_text(tlds_text)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(lines)} names, {len(text)} bytes")
    print(f"wrote {OUT_SHARED.relative_to(ROOT)}: {len(shared)} suffixes, {len(shared_text)} bytes")
    print(f"wrote {OUT_TLDS.relative_to(ROOT)}: {len(tlds)} TLDs, {len(tlds_text.encode())} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
