#!/usr/bin/env python3
"""Build the Android VPN module's bundled assets from data/.

  mobile/modules/cleanway-vpn/android/src/main/assets/popular_veto.txt
    Tranco top-10k MINUS public suffixes / shared platforms. The phone's
    BlockList refuses to block any listed name whose registrable is here —
    a last line of defence against a bad publish. Public suffixes are removed
    on purpose: `github.io` is top-10k, but `evil.github.io` is one tenant's
    site and MUST stay blockable.

Usage: python3 scripts/build_mobile_assets.py [--check]
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOP10K = ROOT / "data" / "top_10k.json"
PSL_TOP = ROOT / "data" / "public_suffixes_in_top.json"
OUT = ROOT / "mobile" / "modules" / "cleanway-vpn" / "android" / "src" / "main" / "assets" / "popular_veto.txt"

# Mirror of scripts/refresh_dangerous_domains.py HOSTING_PLATFORMS ∪ scoring.HOSTING_PLATFORMS
# apexes that are top-10k but whose subdomains are tenants.
SHARED_APEXES = {
    "github.io", "gitlab.io", "blogspot.com", "wordpress.com", "wixsite.com", "weebly.com",
    "webflow.io", "netlify.app", "vercel.app", "pages.dev", "workers.dev", "web.app",
    "firebaseapp.com", "appspot.com", "azurewebsites.net", "herokuapp.com", "cloudfront.net",
    "myshopify.com", "notion.site", "carrd.co", "000webhostapp.com", "duckdns.org", "us.org",
}


def build() -> list[str]:
    raw = json.loads(TOP10K.read_text())
    names = {d.lower() for d in (raw.keys() if isinstance(raw, dict) else raw)}
    psl_top = {d.lower() for d in json.loads(PSL_TOP.read_text())} if PSL_TOP.exists() else set()
    return sorted(names - psl_top - SHARED_APEXES)


def main() -> int:
    lines = build()
    text = "# GENERATED by scripts/build_mobile_assets.py — do not edit\n" + "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(f"STALE: {OUT.relative_to(ROOT)}")
            return 1
        print(f"OK: {len(lines)} names")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(lines)} names, {len(text)} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
